#!/usr/bin/env bash
# Generate the app.dictara.Dictara.Devel Flatpak manifest + metainfo from the
# stable ones. Dev builds (CI on main) ship under this separate app id so they
# are parallel-installable next to the stable app instead of switching the
# user's install over to the dev branch.
#
# Output (gitignored):
#   flatpak/app.dictara.Dictara.Devel.yml
#   flatpak/app.dictara.Dictara.Devel.metainfo.xml

set -euo pipefail
cd "$(dirname "$0")/../flatpak"

{
  echo "# Generated by scripts/gen-devel-manifest.sh — do not edit."
  sed 's/app\.dictara\.Dictara/app.dictara.Dictara.Devel/g' app.dictara.Dictara.yml
} > app.dictara.Dictara.Devel.yml

sed -e 's/app\.dictara\.Dictara/app.dictara.Dictara.Devel/g' \
  -e 's|^  <name>Dictara</name>|  <name>Dictara (Dev)</name>|' \
  app.dictara.Dictara.metainfo.xml > app.dictara.Dictara.Devel.metainfo.xml

echo "Generated flatpak/app.dictara.Dictara.Devel.yml and .metainfo.xml"
